# Generated by Django 2.1.7 on 2019-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snarkalog', '0002_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uniscore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
